name: "D3"
tagline: "Digital Business Solutions"
url: "https://d3moo.is-a.dev"
whatsapp_number_display: "+971 509733299"
whatsapp_link: "https://wa.me/971509733299"
email: "d3@d3moo.is-a.dev"
cal_link: "https://cal.com/d3moo/30min"
og_image: "/assets/img/logo-navy.png"
social:
  instagram: "https://www.instagram.com/d3._group/"
  facebook: "https://www.facebook.com/d3.threedot/"
  linkedin: "https://www.linkedin.com/company/d3dotgroup/"
